-- BigQuery DDL for the PLFS clean tables.
-- Generated by scripts/build_bq_preview.py — DO NOT EDIT BY HAND.
-- See bq_preview/README.md for review notes.

CREATE SCHEMA IF NOT EXISTS `plfs`;

-- ============================================================
-- FACT-ISH TABLES (unioned across all releases)
-- ============================================================

-- persons
CREATE TABLE IF NOT EXISTS `plfs.persons` (
  release_id STRING NOT NULL  OPTIONS(description='Release identifier (e.g. \'calendar_2025\'). Partition key.'),
  release_format STRING NOT NULL  OPTIONS(description='\'annual\' (Jul-Jun) or \'calendar\' (Jan-Dec).'),
  release_year STRING NOT NULL  OPTIONS(description='Human-readable year label, e.g. \'2018-19\' or \'CY2024\'.'),
  catalog_id STRING NOT NULL  OPTIONS(description='microdata.gov.in catalog ID, e.g. \'213\'.'),
  qtr STRING  OPTIONS(description='Quarter code (annual / pre-CY2025 releases).'),
  month STRING  OPTIONS(description='Month code (CY2025 only — replaces qtr).'),
  visit STRING  OPTIONS(description='V1 (first visit) or V2/V3/V4 (revisits).'),
  sec STRING  OPTIONS(description='Sector: 1=Rural, 2=Urban.'),
  st STRING  OPTIONS(description='State/UT code (2-digit). Joins to dim_state.'),
  dc STRING  OPTIONS(description='District code (2-digit, scoped to state). Joins to dim_district.'),
  nss_reg STRING  OPTIONS(description='NSS region code.'),
  strm STRING  OPTIONS(description='Stratum code (resets per state).'),
  sstrm STRING  OPTIONS(description='Sub-stratum code.'),
  ss STRING  OPTIONS(description='Sub-sample (1 or 2).'),
  sro STRING  OPTIONS(description='FOD sub-region code.'),
  mfsu STRING  OPTIONS(description='First Stage Unit (FSU) serial within stratum.'),
  sss STRING  OPTIONS(description='Second Stage Stratum number.'),
  ssu STRING  OPTIONS(description='Sample household number within FSU.'),
  srl_no STRING  OPTIONS(description='Person serial number within household.'),
  rel STRING  OPTIONS(description='Relationship to head. Joins to dim_relation_to_head.'),
  sex STRING  OPTIONS(description='1=Male, 2=Female, 3=Transgender. Joins to dim_sex.'),
  age INT64  OPTIONS(description='Age in completed years.'),
  marst STRING  OPTIONS(description='Marital status. Joins to dim_marital_status.'),
  gedu_lvl STRING  OPTIONS(description='General education code. Joins to dim_general_education.'),
  tedu_lvl STRING  OPTIONS(description='Technical education code. Joins to dim_technical_education.'),
  voc STRING  OPTIONS(description='Vocational/technical training received. Joins to dim_vocational_training_received.'),
  pas STRING  OPTIONS(description='Usual principal activity status code. Joins to dim_activity_status.'),
  ind_pas STRING  OPTIONS(description='Industry (NIC 2008, 5-digit) in principal status.'),
  ocu_pas STRING  OPTIONS(description='Occupation (NCO 2015, 3-digit) in principal status.'),
  etyp_pas STRING  OPTIONS(description='Enterprise type in principal status. Joins to dim_enterprise_type.'),
  ssec_pas STRING  OPTIONS(description='Social security benefits in principal status. Joins to dim_social_security.'),
  job_pas STRING  OPTIONS(description='Job contract type in principal status. Joins to dim_job_contract.'),
  wrkr_pas STRING  OPTIONS(description='Number-of-workers band in principal status. Joins to dim_no_of_workers.'),
  sas STRING  OPTIONS(description='Usual subsidiary activity status code.'),
  ind_sas STRING  OPTIONS(description='Industry code in subsidiary status (5-digit NIC).'),
  ocu_sas STRING  OPTIONS(description='Occupation code in subsidiary status (3-digit NCO).'),
  aps_cws STRING  OPTIONS(description='CWS activity status code.'),
  aind_cws STRING  OPTIONS(description='Industry code in CWS (2-digit NIC division).'),
  ocu_cws STRING  OPTIONS(description='Occupation code in CWS (3-digit NCO).'),
  ern_reg INT64  OPTIONS(description='Monthly earnings for regular salaried/wage activity (₹).'),
  ern_self INT64  OPTIONS(description='Monthly earnings for self-employment (₹).'),
  nss INT64  OPTIONS(description='FSUs surveyed in cell for this sub-sample.'),
  nsc INT64  OPTIONS(description='FSUs surveyed in cell combined across sub-samples.'),
  mult INT64  OPTIONS(description='Sub-sample-wise multiplier (2 implied decimals).'),
  no_qtr INT64  OPTIONS(description='Count of contributing FSUs across quarters.'),
  weight_annual FLOAT64 NOT NULL  OPTIONS(description='Calibrated annual weight per row. Computed at load time via scripts/weights.py based on the release\'s weight_rule. SUM(weight_annual) over a filter gives a weighted-population estimate.')
)
CLUSTER BY release_id;

-- households
CREATE TABLE IF NOT EXISTS `plfs.households` (
  release_id STRING NOT NULL  OPTIONS(description='Release identifier. Partition key.'),
  release_format STRING NOT NULL  OPTIONS(description='\'annual\' or \'calendar\'.'),
  release_year STRING NOT NULL  OPTIONS(description='Year label, e.g. \'2018-19\' or \'CY2024\'.'),
  catalog_id STRING NOT NULL  OPTIONS(description='microdata.gov.in catalog ID.'),
  qtr STRING,
  month STRING,
  visit STRING,
  sec STRING,
  st STRING,
  dc STRING,
  nss_reg STRING,
  strm STRING,
  sstrm STRING,
  ss STRING,
  mfsu STRING,
  sss STRING,
  ssu STRING,
  hh_size INT64  OPTIONS(description='Total household members.'),
  hh_type STRING  OPTIONS(description='Household type. Joins to dim_household_type_rural (sec=1) or dim_household_type_urban (sec=2).'),
  religion STRING  OPTIONS(description='Religion code. Joins to dim_religion.'),
  social_grp STRING  OPTIONS(description='Social group code (ST/SC/OBC/Other). Joins to dim_social_group.'),
  hce_tot INT64  OPTIONS(description='Total household monthly consumer expenditure (₹). PLFS standard income proxy.'),
  hce1 INT64  OPTIONS(description='Consumer goods+services HCE component.'),
  hce2 INT64  OPTIONS(description='Home-grown stock imputed HCE component.'),
  hce3 INT64  OPTIONS(description='Wages-in-kind imputed HCE component.'),
  hce4 INT64  OPTIONS(description='Annual clothing/footwear (1/12 averaged).'),
  hce5 INT64  OPTIONS(description='Annual durables (1/12 averaged).'),
  nss INT64,
  nsc INT64,
  mult INT64,
  no_qtr INT64,
  weight_annual FLOAT64 NOT NULL  OPTIONS(description='Calibrated annual weight per household.')
)
CLUSTER BY release_id;

-- ============================================================
-- DIMENSION TABLES
-- ============================================================

-- releases
CREATE TABLE IF NOT EXISTS `plfs.releases` (
  release_id STRING NOT NULL,
  label STRING NOT NULL,
  format STRING NOT NULL  OPTIONS(description='\'annual\' or \'calendar\'.'),
  year_label STRING NOT NULL,
  period_start STRING NOT NULL  OPTIONS(description='First month of reference period.'),
  period_end STRING NOT NULL  OPTIONS(description='Last month of reference period.'),
  catalog_id STRING NOT NULL,
  catalog_url STRING NOT NULL,
  weight_rule STRING NOT NULL  OPTIONS(description='\'combined\' / \'half_yearly\' / \'simple\' / \'limited\'. See WEIGHTS.md.'),
  input_kind STRING NOT NULL  OPTIONS(description='\'txt\' (fixed-width) / \'csv\' / \'tsv\' — source format.'),
  n_files INT64 NOT NULL,
  file_keys STRING NOT NULL  OPTIONS(description='Pipe-separated list (e.g., \'hhv1|hhrv|perv1|perrv\').')
);

-- dim_state
CREATE TABLE IF NOT EXISTS `plfs.dim_state` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);

-- dim_district
CREATE TABLE IF NOT EXISTS `plfs.dim_district` (
  state_code STRING NOT NULL,
  state_name STRING NOT NULL,
  district_code STRING NOT NULL,
  district_name STRING NOT NULL
);

-- dim_nco_full
CREATE TABLE IF NOT EXISTS `plfs.dim_nco_full` (
  code STRING NOT NULL  OPTIONS(description='8-digit detailed NCO 2015 code (e.g. \'2512.0100\').'),
  description STRING NOT NULL,
  nco_2004_code STRING  OPTIONS(description='Equivalent NCO 2004 code (e.g. \'2132.10\').')
);

-- dim_activity_status
CREATE TABLE IF NOT EXISTS `plfs.dim_activity_status` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_enterprise_type
CREATE TABLE IF NOT EXISTS `plfs.dim_enterprise_type` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_general_education
CREATE TABLE IF NOT EXISTS `plfs.dim_general_education` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_household_type_rural
CREATE TABLE IF NOT EXISTS `plfs.dim_household_type_rural` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_household_type_urban
CREATE TABLE IF NOT EXISTS `plfs.dim_household_type_urban` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_job_contract
CREATE TABLE IF NOT EXISTS `plfs.dim_job_contract` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_marital_status
CREATE TABLE IF NOT EXISTS `plfs.dim_marital_status` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_membership_status
CREATE TABLE IF NOT EXISTS `plfs.dim_membership_status` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nco_division
CREATE TABLE IF NOT EXISTS `plfs.dim_nco_division` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nco_family
CREATE TABLE IF NOT EXISTS `plfs.dim_nco_family` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nco_group
CREATE TABLE IF NOT EXISTS `plfs.dim_nco_group` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nco_subdivision
CREATE TABLE IF NOT EXISTS `plfs.dim_nco_subdivision` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nic_class
CREATE TABLE IF NOT EXISTS `plfs.dim_nic_class` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nic_division
CREATE TABLE IF NOT EXISTS `plfs.dim_nic_division` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nic_group
CREATE TABLE IF NOT EXISTS `plfs.dim_nic_group` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_nic_subclass
CREATE TABLE IF NOT EXISTS `plfs.dim_nic_subclass` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_no_of_workers
CREATE TABLE IF NOT EXISTS `plfs.dim_no_of_workers` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_paid_leave_eligible
CREATE TABLE IF NOT EXISTS `plfs.dim_paid_leave_eligible` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_product_destination
CREATE TABLE IF NOT EXISTS `plfs.dim_product_destination` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_quarter
CREATE TABLE IF NOT EXISTS `plfs.dim_quarter` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_relation_to_head
CREATE TABLE IF NOT EXISTS `plfs.dim_relation_to_head` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_religion
CREATE TABLE IF NOT EXISTS `plfs.dim_religion` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_sector
CREATE TABLE IF NOT EXISTS `plfs.dim_sector` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_sex
CREATE TABLE IF NOT EXISTS `plfs.dim_sex` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_social_group
CREATE TABLE IF NOT EXISTS `plfs.dim_social_group` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_social_security
CREATE TABLE IF NOT EXISTS `plfs.dim_social_security` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_sub_sample
CREATE TABLE IF NOT EXISTS `plfs.dim_sub_sample` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_technical_education
CREATE TABLE IF NOT EXISTS `plfs.dim_technical_education` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_visit
CREATE TABLE IF NOT EXISTS `plfs.dim_visit` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_vocational_training_received
CREATE TABLE IF NOT EXISTS `plfs.dim_vocational_training_received` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_vt_duration
CREATE TABLE IF NOT EXISTS `plfs.dim_vt_duration` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_vt_field_of_training
CREATE TABLE IF NOT EXISTS `plfs.dim_vt_field_of_training` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_vt_funding_source
CREATE TABLE IF NOT EXISTS `plfs.dim_vt_funding_source` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
-- dim_vt_type_of_training
CREATE TABLE IF NOT EXISTS `plfs.dim_vt_type_of_training` (
  code STRING NOT NULL  OPTIONS(description='Zero-padded code as stored in data.'),
  description STRING NOT NULL
);
